sonar.projectKey=visit-all
sonar.projectName=visit-all
sonar.sources=src
sonar.tests=tests
sonar.exclusions=design/**,node_modules/**,.next/**,coverage/**
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
